# test environment

version: '3.4'

services:
  postgres:
    image: postgres:11.0
    container_name: plat-goldenCRM-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: plat-goldenCRM-data
        target: /data
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_INITDB_ARGS=--data-checksums
      - PGDATA=/data

volumes:
  plat-goldenCRM-data: