services:
  postgres:
    image: postgres:9.6
    container_name: plat-files-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: plat-files-pgdata
        target: /data
    environment:
      - POSTGRES_DB=files
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_INITDB_ARGS=--data-checksums
      - PGDATA=/data