CREATE TABLE flats (
  id serial,
  area text,
  land_mark text,
  address text,
  homeNumber integer,
  flat_number smallint,
  price_min integer,
  price_max integer,
  rooms_count smallint,
  rooms_type text,
  floor smallint,
  floor_count smallint,
  square integer,
  flat_type text,
  state text,
  toilet_type text,
  toilet_count smallint,
  build_year smallint,
  is_corner boolean,
  description text,
  owner_name text,
  owner_number text
);
